### ISSUE TITLE
failure Port(15151) not connected

### ISSUE THREAD

**Issue by DaniXXX** [amir1376/ab-download-manager#121]
Download w/o any issues but when I tried to use it I got this message :)  Thank you for checking it out. Danni

"The extension AB Download Manager Browser Integration says
failure Port(15151) not connected"

**Comment by amir1376** [comment]
@DaniXXX Hi there. I think this port is used in your system and doesn't allow the app to use it. you can change it and see the result

to do that 
- go to App Settings `Settings > Browser Integration > Integration Port`
- set the new port value (try another random port in range of 10,000 until 65000.)
- make sure `Browser Integration` is turned `ON`
- now open the `ABDM Browser Extension` settings in your browser 
- change the port to the value you entered in the app
- hit the test again.

Another possibility is that the browser can't access `http://localhost:15151` because there is `VPN` or `proxy` that blocks your browser from accessing that part on your system

**Comment by DaniXXX** [comment]
Thank you that was the issue the VPN. You were very helpful by offering more than 1 solution, it gave me a few things to try and it works . Very grateful.  :)
