### ISSUE TITLE
Custom installation path for Windows exe

### ISSUE THREAD

**Issue by daifiyum** [amir1376/ab-download-manager#127]
Custom installation path for Windows exe

**Comment by amir1376** [comment]
@daifiyum Hi there. 
I disabled it intentionally because I want to implement an auto update feature. (something like discord)
and it will not work if user installs the app in a folder that process can't edit (for example only administrators can edit files in `C://Program Files` )

BTW you can use the `zip file` and extract it where ever you wish.
