### ISSUE TITLE
Can't Auto Detect Videos to Download!

### ISSUE THREAD

**Issue by DeMoN100** [amir1376/ab-download-manager#131]
Hello there,

I am trying this for the first time coming from IDM I would like to say I hope that this becomes compatible for windows 7 as this does not work for windows universally. I had to use Vxkex to get this to run which after doing so it seems nice but the popup to download does not appear when you click a video to play. I tried on multiple websites & you should be able to get the download selected popup when you click play on a video.

**Comment by amir1376** [comment]
@DeMoN100 Hi there
- About the windows 7 that you mentioned, unfortunately I can't do something about that because this app is built using [Compose Multiplatform framework](https://github.com/JetBrains/compose-multiplatform/) so this app can work where ever that framework can.
- About the video downloading: please see #9
