### ISSUE TITLE
Failed to Download from Kotlin Multiplatform Wizard

### ISSUE THREAD

**Issue by zczhendev** [amir1376/ab-download-manager#222]
Description:
Using [Downloader Name] to download files from the website [https://kmp.jetbrains.com/?_gl=11kx0g3j_gcl_auMTM5ODA4NDAwMi4xNzMyNTI3MjUxFPAUMTM5ODA4NDAwMi4xNzMyNTI3MjUx_gaMTcxODQ3ODI4OC4xNzIzNDQ3NzYx_ga_9J976DJZ68*MTczMjUyNzI1Mi4xOC4xLjE3MzI1MjczOTYuNjAuMC4w] results in a failed download. However, the same file can be downloaded successfully using the Chrome browser.

Steps to Reproduce:

Use the following URL to start downloading: Kotlin Multiplatform Wizard.
Configure project generation parameters.
Start the download and observe the outcome.
Expected Behavior:
The downloader should successfully retrieve the content from the website, just like the browser.

Actual Behavior:
The downloader displays a download failure and does not retrieve any file.

Environment Information:

Downloader version: [Please fill in]
Operating system: [Please fill in, e.g., Windows 10]
Network environment: [e.g., Corporate network / China Telecom / Using Clash to connect to a foreign network]

**Comment by amir1376** [comment]
Hi dear. I tested it. and it has no problem. 

![image](https://github.com/user-attachments/assets/ebdad40a-46d2-49f4-840f-35e49ced92e7)

I think that this URL is restricted in your area
so be sure to also enable proxy in the ABDownloadManager settings too! 
in order to do that 
goto `Settings` > `Download Engine` > `Use Proxy`
