### ISSUE TITLE
QOL: Pause and Cancel download

### ISSUE THREAD

**Issue by CatPieLeaf** [amir1376/ab-download-manager#244]
**Just a small QOL feature:**
Splitting the Pause button into two: Cancel and pause.

If the download is cancelled by the user, its remaining files are removed from the disk and the cancelled download won't appear on the list.

In the current behaviour, the download is ALWAYS paused whenever cancelled, and not deleted from the disk. Even though its a non-resumable download. forcing the user to manually close the UI and delete the download from the downloads list.

**Resuming non-resumable downloads:**
If a download is marked as non-resumable, and the user tries to resume, the manager could display a prompt asking the user if it wants to cancel the download or change the download link for attempting to resume.

If not possible, the manager could not even offer the pause button in case a download is non-resumable.

**Comment by amir1376** [comment]
Hi. thanks for your suggestion.

> Splitting the Pause button into two: Cancel and pause.
If the download is cancelled by the user, its remaining files are removed from the disk and the cancelled download won't appear on the list.

this will confuse the user because `Cancel` meant to be used for "Pause And Close" not to remove that download. if we want to remove it we should explicitly say it `Remove`.

> Resuming non-resumable downloads:
If a download is marked as non-resumable, and the user tries to resume, the manager could display a prompt asking the user if it wants to cancel the download or change the download link for attempting to resume.
If not possible, the manager could not even offer the pause button in case a download is non-resumable.

user will be notified if he/she pressed on `Pause` if the download does not support resume. but since some servers may behave diffidently in different times/requests (specially web servers that behind a load balancer or reverse proxy like cloudflare etc..) they may successfully support resume later. in this way user has a chance to resume it later. if resume is not supported that time too, then the download simply will be started over
