### ISSUE TITLE
File not recognized

### ISSUE THREAD

**Issue by andymachs** [amir1376/ab-download-manager#271]
File not recognized.
PDF file link:
https://www.murata.com/en-us/api/pdfdownloadapi?cate=luCeramicCapacitorsSMD&partno=GRM1552C1H331GA01%23

![image](https://github.com/user-attachments/assets/4aff2ba1-9500-4232-864e-effea68bfe42)

**Comment by amir1376** [comment]
Hi dear. 
There is no problem. You can press on "Download" and it works!

the reason you see "Unknown" is that some web servers does not provide file size from the beginning.
these files usually not support resuming as well.

**Comment by andymachs** [comment]
Could you increase the speed of recognize? Current it is slow, especially larger files.

**Comment by amir1376** [comment]
> Could you increase the speed of recognize? Current it is slow, especially larger files.

I didn't change the speed of recognition of the filename.
first app tries to find the filename from the webserver. (which has a delay based  your internet connection)

I only disable download until the first response was received.
then if the server gives me a filename I use it. as a fallback I will try to find best name by the download url instead.(default)
I intentionally disable `Downlaod` button at the beginning because some users trying to start the  download when the filename is not determined yet. (for example which is common in github releases that end of the link is something like a hash `exemple.com/downloads/abcde-efgr-afsda-asdafaw` instead of the real filename )
