### ISSUE TITLE
Unable to change the download location

### ISSUE THREAD

**Issue by arunss0** [amir1376/ab-download-manager#314]
Team, I have changed the default download location from _"C:\Users\<username>\Downloads\"_ to _"D:\Downloads"_ in the settings, but even though every time it pops up with this _"C:\Users\<username>\Downloads\"_ path.

I also tried moving the Downloads folder from C to D by using this ![image](https://github.com/user-attachments/assets/9754acbd-e3e8-4e00-bb7e-6623e16498f1) option, but no luck.

1. please fix the default Downloads folder settings not reflecting issue
2. And please use like this `(New-Object -ComObject Shell.Application).NameSpace('shell:Downloads').Self.Path` PowerShell command to fetch the exact Downloads folder instead of using the `%USERPROFILE%\Downloads`

**Comment by amir1376** [comment]
Hi dear. 

> please fix the default Downloads folder settings not reflecting issue

This is because category download locations not synced after changing download  location
which is fixed now. ( in #320 )


> And please use like this (New-Object -ComObject Shell.Application).NameSpace('shell:Downloads').Self.Path PowerShell command to fetch the exact Downloads folder instead of using the %USERPROFILE%\Downloads

Thanks for your suggestion however 

- because this app has its own download location, it adds extra complexity to keep Windows default download location synced with the app.
- and also this is a multiplatform app and also other platforms doesn't has this feature

because of these I prefer to use the simpler approach for now.
