### ISSUE TITLE
Winget package

### ISSUE THREAD

**Issue by sitiom** [amir1376/ab-download-manager#34]
- Related to #13

Issue to track the status of the Winget Package:

- https://github.com/microsoft/winget-pkgs/issues/168082
- https://github.com/microsoft/winget-pkgs/pull/168098
- #35

**Comment by amir1376** [comment]
@sitiom Hi. I really thanks for your PR and contribution
Unfortunately there are some issues at the moment with the `compose's default msi installer (wix)` that Im using. 
please see  #47 

If they didn't fix these .I'll have to setup a custom installer instead of [default one](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Native_distributions_and_local_execution/README.md#basic-usage)
until then its not possible to publish it there as may have bad UX for users

**Comment by sitiom** [comment]
Can you add install instructions for winget and scoop on your website? (`winget install abdownloadmanager` or `scoop install abdownloadmanager`)

**Comment by amir1376** [comment]
Of course. I will add it to repository's `README.md` for now.
