### ISSUE TITLE
浏览器扩展

### ISSUE THREAD

**Issue by suxiangyv** [amir1376/ab-download-manager#80]
啥时候给个Eage浏览器的扩展呀

**Comment by amir1376** [comment]
@suxiangyv Hi dear. please speak English here so I can understand your issue.

**Comment by suxiangyv** [comment]
I hope Microsoft Edge can also have this plugin

**Comment by amir1376** [comment]
@suxiangyv Hi dear. you can use the extension for Edge using [chrome web store](https://chromewebstore.google.com/detail/ab-download-manager-brows/bbobopahenonfdgjgaleledndnnfhooj?authuser=0&hl=en). because Edge is also a `Chromium Browser` however I will add it to Microsoft Edge Store ( this is duplicate of #31 )
