### ISSUE TITLE
Batch renaming files as sequential numbers when downloading them

### ISSUE THREAD

**Issue by Revilak** [amir1376/ab-download-manager#90]
Hello,
thank you for releasing AB Download Manager, it's a very good software. Would it be possible to implement the feature described in the title so the files are automatically renamed as sequential numbers when downloading them  ? (i.e   0001.(ext), 0002. (ext), 0003. (ext) and so on)
I think that DownThemAll! browser addon is the only one at the moment that can rename files as sequential numbers as I have described above and  the rename mask is 0(asterisk)idx(asterisk).(asterisk)ext(asterisk) (for some reason Github doesn't show the asterisk symbol)
Other renaming masks are described here  https://www.downthemall.org/howto/help/english-menu/renaming-mask/ 
In my opinion using a external download manager like AB Download Manager is more efficient than using a browser addon. Also DownThemAll! latest update is dated January 29, 2024 so it seems pretty abandoned. Furthermore on Google Chrome web store is written "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions."
I'm cataloging my videogames library and I need to download the videogames' screenshots as 0001.jpg, 0002.jpg, 0003.jpg and so on from Gamepressure website. i.e for Frostpunk 2  from https://www.gamepressure.com/games/screenshots_list.asp?ID=21399 so a renaming mask field before starting the download would accomplish the task.
Just as example I attach a screenshot with DownThemAll! fields before starting a download.

![DownThemAll! fields before starting the download](https://github.com/user-attachments/assets/52cc9d19-b568-4450-b93d-d51c67f9f64e)

**Comment by amir1376** [comment]
@Revilak Hi there. thank you for suggestion. I was thinking about that

I think this is not related to a downloader. and also not used by majority of users, but instead it adds some complexity for them

because this option should be added in the Import list page (which all users interact with) and lots of people don't know what that is and how it works.

I think you should consider using [PowerToys](https://github.com/microsoft/PowerToys)
- Download all files that you need to a specific folder.
- Open that folder in `File Explorer` 
- When you installed the `Powertoys Utility` you can see a `Batch Rename` option in the right click menu (which is whats you need)

**Comment by Revilak** [comment]
Thanks for the hint.
Regards
